// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VivaPanamaApi.Data;

#nullable disable

namespace VivaPanamaApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VivaPanamaApi.Models.ActividadItinerario", b =>
                {
                    b.Property<int>("id_actividad_itinerario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_actividad_itinerario"));

                    b.Property<int>("actividadid_actividad")
                        .HasColumnType("integer");

                    b.Property<decimal?>("costo_real")
                        .HasColumnType("numeric");

                    b.Property<int>("diaid_dia")
                        .HasColumnType("integer");

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeSpan?>("hora_fin")
                        .HasColumnType("interval");

                    b.Property<TimeSpan?>("hora_inicio")
                        .HasColumnType("interval");

                    b.Property<int>("id_actividad")
                        .HasColumnType("integer");

                    b.Property<int>("id_dia")
                        .HasColumnType("integer");

                    b.Property<string>("notas_actividad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("orden")
                        .HasColumnType("integer");

                    b.HasKey("id_actividad_itinerario");

                    b.HasIndex("actividadid_actividad");

                    b.HasIndex("diaid_dia");

                    b.ToTable("actividad_itinerario");
                });

            modelBuilder.Entity("VivaPanamaApi.Models.ActividadLugar", b =>
                {
                    b.Property<int>("id_actividad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_actividad"));

                    b.Property<decimal?>("costo_actividad")
                        .HasColumnType("numeric");

                    b.Property<string>("descripcion_actividad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("dificultad_actividad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("duracion_estimada")
                        .HasColumnType("integer");

                    b.Property<string>("equipo_requerido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeSpan?>("horario_apertura")
                        .HasColumnType("interval");

                    b.Property<TimeSpan?>("horario_cierre")
                        .HasColumnType("interval");

                    b.Property<int>("id_lugar")
                        .HasColumnType("integer");

                    b.Property<string>("nombre_actividad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("restricciones")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id_actividad");

                    b.HasIndex("id_lugar");

                    b.ToTable("actividad_lugar");
                });

            modelBuilder.Entity("VivaPanamaApi.Models.Calificacion", b =>
                {
                    b.Property<int>("id_calificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_calificacion"));

                    b.Property<string>("comentario")
                        .HasColumnType("text");

                    b.Property<DateTime?>("fecha_calificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("id_entidad")
                        .HasColumnType("integer");

                    b.Property<int>("id_usuario")
                        .HasColumnType("integer");

                    b.Property<int>("puntuacion")
                        .HasColumnType("integer");

                    b.Property<string>("tipo_entidad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("usuarioid_usuario")
                        .HasColumnType("integer");

                    b.HasKey("id_calificacion");

                    b.HasIndex("usuarioid_usuario");

                    b.ToTable("calificacion");
                });

            modelBuilder.Entity("VivaPanamaApi.Models.DiaItinerario", b =>
                {
                    b.Property<int>("id_dia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_dia"));

                    b.Property<int>("Itinerarioid_itinerario")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("fecha_dia")
                        .HasColumnType("date");

                    b.Property<int>("id_itinerario")
                        .HasColumnType("integer");

                    b.Property<string>("notas_dia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("numero_dia")
                        .HasColumnType("integer");

                    b.Property<decimal?>("presupuesto_dia")
                        .HasColumnType("numeric");

                    b.HasKey("id_dia");

                    b.HasIndex("Itinerarioid_itinerario");

                    b.ToTable("dia_itinerario");
                });

            modelBuilder.Entity("VivaPanamaApi.Models.Favorito", b =>
                {
                    b.Property<int>("id_favorito")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_favorito"));

                    b.Property<int>("Usuarioid_usuario")
                        .HasColumnType("integer");

                    b.Property<DateTime>("fecha_agregado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("id_entidad")
                        .HasColumnType("integer");

                    b.Property<int>("id_usuario")
                        .HasColumnType("integer");

                    b.Property<string>("notas")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("tipo_entidad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id_favorito");

                    b.HasIndex("Usuarioid_usuario");

                    b.ToTable("favorito");
                });

            modelBuilder.Entity("VivaPanamaApi.Models.Hotel", b =>
                {
                    b.Property<int>("id_hotel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_hotel"));

                    b.Property<decimal?>("calificacion_promedio")
                        .HasColumnType("numeric");

                    b.Property<string>("descripcion_hotel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("id_lugar")
                        .HasColumnType("integer");

                    b.Property<string>("nombre_hotel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("precio_noche")
                        .HasColumnType("numeric");

                    b.Property<string>("servicios_hotel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("telefono_hotel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id_hotel");

                    b.HasIndex("id_lugar");

                    b.ToTable("hotel");
                });

            modelBuilder.Entity("VivaPanamaApi.Models.HotelItinerario", b =>
                {
                    b.Property<int>("id_hotel_itinerario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_hotel_itinerario"));

                    b.Property<decimal?>("costo_total")
                        .HasColumnType("numeric");

                    b.Property<int?>("dia_itinerarioid_dia")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("fecha_checkin")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("fecha_checkout")
                        .HasColumnType("date");

                    b.Property<int?>("hotelid_hotel")
                        .HasColumnType("integer");

                    b.Property<int>("id_dia")
                        .HasColumnType("integer");

                    b.Property<int>("id_hotel")
                        .HasColumnType("integer");

                    b.Property<string>("notas_hospedaje")
                        .HasColumnType("text");

                    b.Property<int?>("numero_noches")
                        .HasColumnType("integer");

                    b.HasKey("id_hotel_itinerario");

                    b.HasIndex("dia_itinerarioid_dia");

                    b.HasIndex("hotelid_hotel");

                    b.ToTable("hotel_itinerario");
                });

            modelBuilder.Entity("VivaPanamaApi.Models.Itinerario", b =>
                {
                    b.Property<int>("id_itinerario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_itinerario"));

                    b.Property<string>("descripcion_itinerario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("es_publico")
                        .HasColumnType("boolean");

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("fecha_creacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("fecha_fin")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("fecha_inicio")
                        .HasColumnType("date");

                    b.Property<int>("id_usuario")
                        .HasColumnType("integer");

                    b.Property<string>("nombre_itinerario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("presupuesto_total")
                        .HasColumnType("numeric");

                    b.HasKey("id_itinerario");

                    b.HasIndex("id_usuario");

                    b.ToTable("itinerario");
                });

            modelBuilder.Entity("VivaPanamaApi.Models.Lugar", b =>
                {
                    b.Property<int>("id_Lugar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_Lugar"));

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("mombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("provincia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("tipo_lugar")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id_Lugar");

                    b.ToTable("lugar", (string)null);
                });

            modelBuilder.Entity("VivaPanamaApi.Models.LugarItinerario", b =>
                {
                    b.Property<int>("id_lugar_itinerario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_lugar_itinerario"));

                    b.Property<int?>("dia_itinerarioid_dia")
                        .HasColumnType("integer");

                    b.Property<int>("id_dia")
                        .HasColumnType("integer");

                    b.Property<int>("id_lugar")
                        .HasColumnType("integer");

                    b.Property<int?>("lugarid_Lugar")
                        .HasColumnType("integer");

                    b.Property<string>("notas_visita")
                        .HasColumnType("text");

                    b.Property<int?>("orden_visita")
                        .HasColumnType("integer");

                    b.Property<int?>("tiempo_estimado_visita")
                        .HasColumnType("integer");

                    b.HasKey("id_lugar_itinerario");

                    b.HasIndex("dia_itinerarioid_dia");

                    b.HasIndex("lugarid_Lugar");

                    b.ToTable("lugar_itinerario");
                });

            modelBuilder.Entity("VivaPanamaApi.Models.PreferenciasUsuario", b =>
                {
                    b.Property<int>("id_preferencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_preferencia"));

                    b.Property<int>("id_usuario")
                        .HasColumnType("integer");

                    b.Property<string>("intereses")
                        .HasColumnType("text");

                    b.Property<string>("nivel_actividad")
                        .HasColumnType("text");

                    b.Property<decimal?>("presupuesto_maximo")
                        .HasColumnType("numeric");

                    b.Property<string>("tipo_alojamiento_preferido")
                        .HasColumnType("text");

                    b.Property<string>("tipo_viajero")
                        .HasColumnType("text");

                    b.Property<int?>("usuarioid_usuario")
                        .HasColumnType("integer");

                    b.HasKey("id_preferencia");

                    b.HasIndex("usuarioid_usuario");

                    b.ToTable("preferencias_usuario");
                });

            modelBuilder.Entity("VivaPanamaApi.Models.Restaurante", b =>
                {
                    b.Property<int>("id_restaurante")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_restaurante"));

                    b.Property<decimal?>("calificacion_promedio")
                        .HasColumnType("numeric");

                    b.Property<string>("descripcion_restaurante")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeSpan?>("horario_apertura")
                        .HasColumnType("interval");

                    b.Property<TimeSpan?>("horario_cierre")
                        .HasColumnType("interval");

                    b.Property<int>("id_lugar")
                        .HasColumnType("integer");

                    b.Property<string>("nombre_restaurante")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("precio_promedio")
                        .HasColumnType("numeric");

                    b.Property<string>("tipo_cocina_restaurante")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id_restaurante");

                    b.HasIndex("id_lugar");

                    b.ToTable("restaurante");
                });

            modelBuilder.Entity("VivaPanamaApi.Models.RestauranteItinerario", b =>
                {
                    b.Property<int>("id_restaurante_itinerario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_restaurante_itinerario"));

                    b.Property<decimal?>("costo_estimado")
                        .HasColumnType("numeric");

                    b.Property<int?>("dia_itinerarioid_dia")
                        .HasColumnType("integer");

                    b.Property<TimeSpan?>("hora_reserva")
                        .HasColumnType("interval");

                    b.Property<int>("id_dia")
                        .HasColumnType("integer");

                    b.Property<int>("id_restaurante")
                        .HasColumnType("integer");

                    b.Property<string>("notas_restaurante")
                        .HasColumnType("text");

                    b.Property<int?>("numero_personas")
                        .HasColumnType("integer");

                    b.Property<int?>("restauranteid_restaurante")
                        .HasColumnType("integer");

                    b.Property<string>("tipo_comida")
                        .HasColumnType("text");

                    b.HasKey("id_restaurante_itinerario");

                    b.HasIndex("dia_itinerarioid_dia");

                    b.HasIndex("restauranteid_restaurante");

                    b.ToTable("restaurante_itinerario");
                });

            modelBuilder.Entity("VivaPanamaApi.Models.Usuario", b =>
                {
                    b.Property<int>("id_usuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_usuario"));

                    b.Property<string>("cedula_pasaporte")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("edad_usuario")
                        .HasColumnType("integer");

                    b.Property<string>("email_usuario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("nombre_usuario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id_usuario");

                    b.ToTable("usuario", (string)null);
                });

            modelBuilder.Entity("VivaPanamaApi.Models.imagen", b =>
                {
                    b.Property<int>("id_imagen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_imagen"));

                    b.Property<string>("descripcion_imagen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("es_principal")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("fecha_subida")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("id_entidad")
                        .HasColumnType("integer");

                    b.Property<string>("tipo_entidad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("url_imagen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id_imagen");

                    b.ToTable("imagen");
                });

            modelBuilder.Entity("VivaPanamaApi.Models.registro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Fecha_Entrada")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Fecha_Salida")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Id_Lugar")
                        .HasColumnType("integer");

                    b.Property<int>("Id_Usuario")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Id_Lugar");

                    b.HasIndex("Id_Usuario");

                    b.ToTable("registro", (string)null);
                });

            modelBuilder.Entity("VivaPanamaApi.Models.ActividadItinerario", b =>
                {
                    b.HasOne("VivaPanamaApi.Models.ActividadLugar", "actividad")
                        .WithMany()
                        .HasForeignKey("actividadid_actividad")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VivaPanamaApi.Models.DiaItinerario", "dia")
                        .WithMany("Actividades")
                        .HasForeignKey("diaid_dia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("actividad");

                    b.Navigation("dia");
                });

            modelBuilder.Entity("VivaPanamaApi.Models.ActividadLugar", b =>
                {
                    b.HasOne("VivaPanamaApi.Models.Lugar", "Lugar")
                        .WithMany()
                        .HasForeignKey("id_lugar")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lugar");
                });

            modelBuilder.Entity("VivaPanamaApi.Models.Calificacion", b =>
                {
                    b.HasOne("VivaPanamaApi.Models.Usuario", "usuario")
                        .WithMany()
                        .HasForeignKey("usuarioid_usuario");

                    b.Navigation("usuario");
                });

            modelBuilder.Entity("VivaPanamaApi.Models.DiaItinerario", b =>
                {
                    b.HasOne("VivaPanamaApi.Models.Itinerario", "Itinerario")
                        .WithMany("Dias")
                        .HasForeignKey("Itinerarioid_itinerario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Itinerario");
                });

            modelBuilder.Entity("VivaPanamaApi.Models.Favorito", b =>
                {
                    b.HasOne("VivaPanamaApi.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("Usuarioid_usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("VivaPanamaApi.Models.Hotel", b =>
                {
                    b.HasOne("VivaPanamaApi.Models.Lugar", "Lugar")
                        .WithMany()
                        .HasForeignKey("id_lugar")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lugar");
                });

            modelBuilder.Entity("VivaPanamaApi.Models.HotelItinerario", b =>
                {
                    b.HasOne("VivaPanamaApi.Models.DiaItinerario", "dia_itinerario")
                        .WithMany("Hoteles")
                        .HasForeignKey("dia_itinerarioid_dia");

                    b.HasOne("VivaPanamaApi.Models.Hotel", "hotel")
                        .WithMany()
                        .HasForeignKey("hotelid_hotel");

                    b.Navigation("dia_itinerario");

                    b.Navigation("hotel");
                });

            modelBuilder.Entity("VivaPanamaApi.Models.Itinerario", b =>
                {
                    b.HasOne("VivaPanamaApi.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("id_usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("VivaPanamaApi.Models.LugarItinerario", b =>
                {
                    b.HasOne("VivaPanamaApi.Models.DiaItinerario", "dia_itinerario")
                        .WithMany("Lugares")
                        .HasForeignKey("dia_itinerarioid_dia");

                    b.HasOne("VivaPanamaApi.Models.Lugar", "lugar")
                        .WithMany()
                        .HasForeignKey("lugarid_Lugar");

                    b.Navigation("dia_itinerario");

                    b.Navigation("lugar");
                });

            modelBuilder.Entity("VivaPanamaApi.Models.PreferenciasUsuario", b =>
                {
                    b.HasOne("VivaPanamaApi.Models.Usuario", "usuario")
                        .WithMany()
                        .HasForeignKey("usuarioid_usuario");

                    b.Navigation("usuario");
                });

            modelBuilder.Entity("VivaPanamaApi.Models.Restaurante", b =>
                {
                    b.HasOne("VivaPanamaApi.Models.Lugar", "Lugar")
                        .WithMany()
                        .HasForeignKey("id_lugar")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lugar");
                });

            modelBuilder.Entity("VivaPanamaApi.Models.RestauranteItinerario", b =>
                {
                    b.HasOne("VivaPanamaApi.Models.DiaItinerario", "dia_itinerario")
                        .WithMany("Restaurantes")
                        .HasForeignKey("dia_itinerarioid_dia");

                    b.HasOne("VivaPanamaApi.Models.Restaurante", "restaurante")
                        .WithMany()
                        .HasForeignKey("restauranteid_restaurante");

                    b.Navigation("dia_itinerario");

                    b.Navigation("restaurante");
                });

            modelBuilder.Entity("VivaPanamaApi.Models.registro", b =>
                {
                    b.HasOne("VivaPanamaApi.Models.Lugar", "Lugar")
                        .WithMany()
                        .HasForeignKey("Id_Lugar")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Registro_Lugar");

                    b.HasOne("VivaPanamaApi.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("Id_Usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Registro_Usuario");

                    b.Navigation("Lugar");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("VivaPanamaApi.Models.DiaItinerario", b =>
                {
                    b.Navigation("Actividades");

                    b.Navigation("Hoteles");

                    b.Navigation("Lugares");

                    b.Navigation("Restaurantes");
                });

            modelBuilder.Entity("VivaPanamaApi.Models.Itinerario", b =>
                {
                    b.Navigation("Dias");
                });
#pragma warning restore 612, 618
        }
    }
}
